apiVersion: apps/v1
kind: Deployment
metadata:
  name: astonvilla-be-deployment
  labels:
    app: astonvilla-be
spec:
  replicas: 3
  selector:
    matchLabels:
      app: astonvilla-be
  template:
    metadata:
      labels:
        app: astonvilla-be
    spec:
      containers:
      - name: astonvilla-be
        image: akrout97/astonvilla-be
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: astonvilla-be
spec:
  type: NodePort
  selector:
    app: astonvilla-be
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 30001